#!/usr/bin/env python

import rospy
from drone_keyboard_teleop.keyboard_teleop_base import KeyboardTeleop
from drone_keyboard_teleop.ardrone import ArDroneKeyboardTeleop
from drone_keyboard_teleop.bebop import BebopKeyboardTeleop


if __name__ == '__main__':
    rospy.init_node('drone_keyboard_teleop', anonymous=True)

    namespace = rospy.get_namespace()

    model = rospy.get_param('~model', None)
    if model == 'ar_drone':
        teleop = ArDroneKeyboardTeleop(namespace)
    elif model == 'bebop':
        teleop = BebopKeyboardTeleop(namespace)
    else:
        teleop = KeyboardTeleop(namespace)

    teleop.run()